### ISSUE TITLE
High resolution with larger displacement

### ISSUE THREAD

**Issue by YaoooLiang** [alex04072000/CyclicGen#1]
Hi, @alex04072000 
Thank you for your great work!
When I test your model on  high resolution image with larger displacement, the interpolated frame became blurry. As this sample shows （1080 * 1920）:

![sample](https://user-images.githubusercontent.com/38717829/50325967-b4b07180-0522-11e9-9e24-df80aed7073d.png)

Would you give some ideas about this issue? Using traing datasets with larger displacement or enlarging receptive field?

**Comment by alex04072000** [comment]
Thank you for being interested in our work.
This blurry result is caused by exteremely large motions. The motions shown here are even larger than the receptive field of the network. There will be 2 straight forward solutions for this problem. 1) Train a larger network with more layers to increase the receptive field. 2) Downscale the input frame pair. As our main target is UCF-101 dataset, the receptive field of our baseline model is quite small.

**Comment by YaoooLiang** [comment]
Thanks for your suggestions.
The two-stage framework proposed in your paper is very different from bidirectional-optical-flow-based  and make it much easier for interpotation. 
It might be possible to come up with more new approaches based on this framework.

**Comment by YaoooLiang** [comment]
Hi, @alex04072000 
What do you think that using CtxSyn as basemode instead of DVF?

**Comment by alex04072000** [comment]
@YaoooLiang 
I think using a stronger baseline model indeed will lead to a better result. Although the GPU memory usage during training might become unacceptable and result in OOM.

**Comment by scholltan** [comment]
> CtxSyn
@YaoooLiang
hi, coulld you tell the full name of CtxSyn?

**Comment by YaoooLiang** [comment]
> > CtxSyn
> > @YaoooLiang
> > hi, coulld you tell the full name of CtxSyn?

http://web.cecs.pdx.edu/~fliu/project/ctxsyn/
