### ISSUE TITLE
Wrong pixel scale for VGGnet

### ISSUE THREAD

**Issue by mrchizx** [alex04072000/CyclicGen#8]
Hi,

I just noticed that for the whole algorithm, the pixel values for network input/output are scaled to -1 to 1. However, The VGG16 network is supposed to take input tensors with pixel range 0 to 255. The following code in the vgg16.py scales the pixel range to -510 to 0:

rgb_scaled = tf.subtract((input_image+tf.ones_like(input_image)),2)*255.

The VGG weights are set as constant and not trained. I doubt that the VGG net is not able to extract proper features for the edge information because of the wrong scaling. So problem rises that if the VGG net is really needed for edge-guided purposes, or edge information is not helping for this algorithm?

**Comment by alex04072000** [comment]
You're right!
You found a bug in the current implementation. We didn't notice this problem during training. Because the pre-trained and fixed HED network somehow generated reasonable edge-maps with wrong-scaled input images, which can be seen using Tensorboard. Although the detected edges may not be as sharp as being feed with correct-scaled input images. Also, in the ablation studies, we conduct an experiment to show that this edge information (however, with wrong scale) may help the network to produce better results. We believe that using the correct-scaled images, CyclicGen may benefits more from the edge information and leads to a better results in PSNR/SSIM. However, we will leave this bug here for the reproducibility of our AAAI paper. Thank you very much for your report!

**Comment by mrchizx** [comment]
I guess you wanted to put tf.divide but mistakenly typed tf.subtract. :)
Anyways, interesting idea and nice work. Enjoyed reading the paper.
